import Colors from './colors';

export enum EBackground {
  'BACKGROUND_APP' = 'BACKGROUND_APP',
  'BACKGROUND_1' = 'BACKGROUND_1',
  'BACKGROUND_1_ACTIVE' = 'BACKGROUND_1_ACTIVE',
  'BACKGROUND_2' = 'BACKGROUND_2',
  'BACKGROUND_2_ACTIVE' = 'BACKGROUND_2_ACTIVE',
  'BACKGROUND_3' = 'BACKGROUND_3',
  'BACKGROUND_3_ACTIVE' = 'BACKGROUND_3_ACTIVE',
  'BACKGROUND_INVERSE' = 'BACKGROUND_INVERSE',
  'BACKGROUND_BRAND' = 'BACKGROUND_BRAND',
  'BACKGROUND_INFORMATION' = 'BACKGROUND_INFORMATION',
  'BACKGROUND_SUCCESS' = 'BACKGROUND_SUCCESS',
  'BACKGROUND_ERROR' = 'BACKGROUND_ERROR',
  'BACKGROUND_WARNING' = 'BACKGROUND_WARNING',
  'BACKGROUND_CARD' = 'BACKGROUND_CARD_BACKGROUND',
  'BACKGROUND_ALPHA' = 'BACKGROUND_ALPHA',
}

export const BACKGROUND = {
  dark: {
    [EBackground.BACKGROUND_APP]: Colors.gray_100,
    [EBackground.BACKGROUND_1]: Colors.gray_100,
    [EBackground.BACKGROUND_1_ACTIVE]: Colors.gray_95,
    [EBackground.BACKGROUND_2]: Colors.gray_92,
    [EBackground.BACKGROUND_2_ACTIVE]: Colors.gray_90,
    [EBackground.BACKGROUND_3]: Colors.gray_90,
    [EBackground.BACKGROUND_3_ACTIVE]: Colors.gray_85,
    [EBackground.BACKGROUND_INVERSE]: Colors.gray_8,
    [EBackground.BACKGROUND_BRAND]: Colors.yellow_50,
    [EBackground.BACKGROUND_INFORMATION]: Colors.blue_85,
    [EBackground.BACKGROUND_SUCCESS]: Colors.green_90,
    [EBackground.BACKGROUND_ERROR]: Colors.red_90,
    [EBackground.BACKGROUND_WARNING]: Colors.orange_90,
    [EBackground.BACKGROUND_CARD]: Colors.white_a5,
    [EBackground.BACKGROUND_ALPHA]: Colors.white_a0,
  },
  light: {
    [EBackground.BACKGROUND_APP]: Colors.white_a100,
    [EBackground.BACKGROUND_1]: Colors.gray_5,
    [EBackground.BACKGROUND_1_ACTIVE]: Colors.white_a5,
    [EBackground.BACKGROUND_2]: Colors.gray_1,
    [EBackground.BACKGROUND_2_ACTIVE]: Colors.gray_5,
    [EBackground.BACKGROUND_3]: Colors.white_a100,
    [EBackground.BACKGROUND_3_ACTIVE]: Colors.black_a5,
    [EBackground.BACKGROUND_INVERSE]: Colors.gray_92,
    [EBackground.BACKGROUND_BRAND]: Colors.yellow_50,
    [EBackground.BACKGROUND_INFORMATION]: Colors.blue_5,
    [EBackground.BACKGROUND_SUCCESS]: Colors.green_5,
    [EBackground.BACKGROUND_ERROR]: Colors.red_5,
    [EBackground.BACKGROUND_WARNING]: Colors.orange_5,
    [EBackground.BACKGROUND_CARD]: Colors.white_a100,
    [EBackground.BACKGROUND_ALPHA]: Colors.black_a3,
  },
};
