import Colors from './colors';
import { EIcon, ICON_COLOR } from './icon';
import { EText, TEXT_COLOR } from './text';

export enum EButtonColor {
  'BUTTON_DISABLE_FILL' = 'BUTTON_DISABLE_FILL',
  'BUTTON_DISABLE_ICON' = 'BUTTON_DISABLE_ICON',
  'BUTTON_DISABLE_TEXT' = 'BUTTON_DISABLE_TEXT',
  'BUTTON_DISABLE_INV_TEXT' = 'BUTTON_DISABLE_INV_TEXT',
  'BUTTON_DISABLE_INV_ICON' = 'BUTTON_DISABLE_INV_ICON',
  'BUTTON_DISABLE_INV_FILL' = 'BUTTON_DISABLE_INV_FILL',
  'BUTTON_GHOST_PRIMARY_TEXT' = 'BUTTON_GHOST_PRIMARY_TEXT',
  'BUTTON_GHOST_PRIMARY_FILL' = 'BUTTON_GHOST_PRIMARY_FILL',
  'BUTTON_GHOST_PRIMARY_ICON' = 'BUTTON_GHOST_PRIMARY_ICON',
  'BUTTON_GHOST_PRIMARY_FILL_ACTIVE' = 'BUTTON_GHOST_PRIMARY_FILL_ACTIVE',
  'BUTTON_GHOST_SECONDARY_TEXT' = 'BUTTON_GHOST_SECONDARY_TEXT',
  'BUTTON_GHOST_SECONDARY_FILL' = 'BUTTON_GHOST_SECONDARY_FILL',
  'BUTTON_GHOST_SECONDARY_ICON' = 'BUTTON_GHOST_SECONDARY_ICON',
  'BUTTON_GHOST_SECONDARY_FILL_ACTIVE' = 'BUTTON_GHOST_SECONDARY_FILL_ACTIVE',
  'BUTTON_PRIMARY_ICON' = 'BUTTON_PRIMARY_ICON',
  'BUTTON_PRIMARY_FILL' = 'BUTTON_PRIMARY_FILL',
  'BUTTON_PRIMARY_TEXT' = 'BUTTON_PRIMARY_TEXT',
  'BUTTON_PRIMARY_FILL_ACTIVE' = 'BUTTON_PRIMARY_FILL_ACTIVE',
  'BUTTON_SECONDARY_ICON' = 'BUTTON_SECONDARY_ICON',
  'BUTTON_SECONDARY_FILL' = 'BUTTON_SECONDARY_FILL',
  'BUTTON_SECONDARY_TEXT' = 'BUTTON_SECONDARY_TEXT',
  'BUTTON_SECONDARY_FILL_ACTIVE' = 'BUTTON_SECONDARY_FILL_ACTIVE',
  'BUTTON_SECONDARY_INV_ICON' = 'BUTTON_SECONDARY_INV_ICON',
  'BUTTON_SECONDARY_INV_FILL' = 'BUTTON_SECONDARY_INV_FILL',
  'BUTTON_SECONDARY_INV_TEXT' = 'BUTTON_SECONDARY_INV_TEXT',
  'BUTTON_SECONDARY_INV_FILL_ACTIVE' = 'BUTTON_SECONDARY_INV_FILL_ACTIVE',
}

export const BUTTON_COLORS: Record<
  'light' | 'dark',
  Record<EButtonColor, string>
> = {
  dark: {
    [EButtonColor.BUTTON_DISABLE_FILL]: Colors.white_a10,
    [EButtonColor.BUTTON_DISABLE_ICON]: ICON_COLOR.dark[EIcon.ICON_DISABLED],
    [EButtonColor.BUTTON_DISABLE_TEXT]: TEXT_COLOR.dark[EText.TEXT_DISABLED],
    [EButtonColor.BUTTON_DISABLE_INV_TEXT]:
      TEXT_COLOR.dark[EText.TEXT_DISABLED],
    [EButtonColor.BUTTON_DISABLE_INV_ICON]:
      ICON_COLOR.dark[EIcon.ICON_DISABLED],
    [EButtonColor.BUTTON_DISABLE_INV_FILL]: Colors.white_a10,
    [EButtonColor.BUTTON_GHOST_PRIMARY_TEXT]: Colors.yellow_40,
    [EButtonColor.BUTTON_GHOST_PRIMARY_FILL]: Colors.white_a0,
    [EButtonColor.BUTTON_GHOST_PRIMARY_ICON]: Colors.yellow_40,
    [EButtonColor.BUTTON_GHOST_PRIMARY_FILL_ACTIVE]: Colors.white_a5,
    [EButtonColor.BUTTON_GHOST_SECONDARY_TEXT]:
      TEXT_COLOR.dark[EText.TEXT_PRIMARY],
    [EButtonColor.BUTTON_GHOST_SECONDARY_FILL]: Colors.white_a0,
    [EButtonColor.BUTTON_GHOST_SECONDARY_ICON]:
      ICON_COLOR.dark[EIcon.ICON_SUBTLE],
    [EButtonColor.BUTTON_GHOST_SECONDARY_FILL_ACTIVE]: Colors.white_a10,
    [EButtonColor.BUTTON_PRIMARY_ICON]: Colors.gray_95,
    [EButtonColor.BUTTON_PRIMARY_FILL]: Colors.yellow_40,
    [EButtonColor.BUTTON_PRIMARY_TEXT]: Colors.gray_100,
    [EButtonColor.BUTTON_PRIMARY_FILL_ACTIVE]: Colors.yellow_60,
    [EButtonColor.BUTTON_SECONDARY_ICON]: ICON_COLOR.dark[EIcon.ICON_SUBTLE],
    [EButtonColor.BUTTON_SECONDARY_FILL]: Colors.white_a15,
    [EButtonColor.BUTTON_SECONDARY_TEXT]: TEXT_COLOR.dark[EText.TEXT_SUBTLE],
    [EButtonColor.BUTTON_SECONDARY_FILL_ACTIVE]: Colors.white_a5,
    [EButtonColor.BUTTON_SECONDARY_INV_ICON]: Colors.gray_90,
    [EButtonColor.BUTTON_SECONDARY_INV_FILL]: Colors.white_a35,
    [EButtonColor.BUTTON_SECONDARY_INV_TEXT]: Colors.gray_100,
    [EButtonColor.BUTTON_SECONDARY_INV_FILL_ACTIVE]: Colors.white_a15,
  },
  light: {
    [EButtonColor.BUTTON_DISABLE_FILL]: Colors.black_a10,
    [EButtonColor.BUTTON_DISABLE_ICON]: ICON_COLOR.light[EIcon.ICON_DISABLED],
    [EButtonColor.BUTTON_DISABLE_TEXT]: TEXT_COLOR.light[EText.TEXT_DISABLED],
    [EButtonColor.BUTTON_DISABLE_INV_TEXT]:
      TEXT_COLOR.light[EText.TEXT_DISABLED],
    [EButtonColor.BUTTON_DISABLE_INV_ICON]:
      ICON_COLOR.light[EIcon.ICON_DISABLED],
    [EButtonColor.BUTTON_DISABLE_INV_FILL]: Colors.black_a10,
    [EButtonColor.BUTTON_GHOST_PRIMARY_TEXT]: Colors.yellow_50,
    [EButtonColor.BUTTON_GHOST_PRIMARY_FILL]: Colors.black_a0,
    [EButtonColor.BUTTON_GHOST_PRIMARY_ICON]: Colors.yellow_50,
    [EButtonColor.BUTTON_GHOST_PRIMARY_FILL_ACTIVE]: Colors.black_a5,
    [EButtonColor.BUTTON_GHOST_SECONDARY_TEXT]:
      TEXT_COLOR.light[EText.TEXT_PRIMARY],
    [EButtonColor.BUTTON_GHOST_SECONDARY_FILL]: Colors.black_a0,
    [EButtonColor.BUTTON_GHOST_SECONDARY_ICON]:
      ICON_COLOR.light[EIcon.ICON_PRIMARY],
    [EButtonColor.BUTTON_GHOST_SECONDARY_FILL_ACTIVE]: Colors.black_a10,
    [EButtonColor.BUTTON_PRIMARY_ICON]: Colors.gray_95,
    [EButtonColor.BUTTON_PRIMARY_FILL]: Colors.yellow_40,
    [EButtonColor.BUTTON_PRIMARY_TEXT]: TEXT_COLOR.light[EText.TEXT_PRIMARY],
    [EButtonColor.BUTTON_PRIMARY_FILL_ACTIVE]: Colors.yellow_60,
    [EButtonColor.BUTTON_SECONDARY_ICON]: ICON_COLOR.light[EIcon.ICON_SUBTLE],
    [EButtonColor.BUTTON_SECONDARY_FILL]: Colors.black_a10,
    [EButtonColor.BUTTON_SECONDARY_TEXT]: TEXT_COLOR.light[EText.TEXT_SUBTLE],
    [EButtonColor.BUTTON_SECONDARY_FILL_ACTIVE]: Colors.black_a20,
    [EButtonColor.BUTTON_SECONDARY_INV_ICON]: Colors.gray_90,
    [EButtonColor.BUTTON_SECONDARY_INV_FILL]: Colors.white_a35,
    [EButtonColor.BUTTON_SECONDARY_INV_TEXT]: Colors.gray_100,
    [EButtonColor.BUTTON_SECONDARY_INV_FILL_ACTIVE]: Colors.white_a10,
  },
};
