import Colors from './colors';

export enum EIcon {
  'ICON_PRIMARY' = 'ICON_PRIMARY',
  'ICON_SUBTLE' = 'ICON_SUBTLE',
  'ICON_SUBTLEST' = 'ICON_SUBTLEST',
  'ICON_DISABLED' = 'ICON_DISABLED',
  'ICON_INVERSE' = 'ICON_INVERSE',
  'ICON_ON_COLOR' = 'ICON_ON_COLOR',
  'ICON_INVERSE_SUBTLE' = 'ICON_INVERSE_SUBTLE',
  'ICON_INFORMATION' = 'ICON_INFORMATION',
  'ICON_SUCCESS' = 'ICON_SUCCESS',
  'ICON_ERROR' = 'ICON_ERROR',
  'ICON_WARNING' = 'ICON_WARNING',
  'ICON_BRAND' = 'ICON_BRAND',
  'ICON_INVERSE_CONSTANT' = 'ICON_INVERSE_CONSTANT',
}

export const ICON_COLOR = {
  dark: {
    [EIcon.ICON_PRIMARY]: Colors.gray_5,
    [EIcon.ICON_SUBTLE]: Colors.gray_50,
    [EIcon.ICON_SUBTLEST]: Colors.gray_60,
    [EIcon.ICON_DISABLED]: Colors.white_a20,
    [EIcon.ICON_ON_COLOR]: Colors.gray_8,
    [EIcon.ICON_INVERSE]: Colors.gray_95,
    [EIcon.ICON_INVERSE_SUBTLE]: Colors.gray_40,
    [EIcon.ICON_INFORMATION]: Colors.blue_30,
    [EIcon.ICON_SUCCESS]: Colors.green_60,
    [EIcon.ICON_ERROR]: Colors.red_50,
    [EIcon.ICON_WARNING]: Colors.orange_50,
    [EIcon.ICON_BRAND]: Colors.yellow_50,
    [EIcon.ICON_INVERSE_CONSTANT]: Colors.gray_100,
  },
  light: {
    [EIcon.ICON_PRIMARY]: Colors.gray_95,
    [EIcon.ICON_SUBTLE]: Colors.gray_50,
    [EIcon.ICON_SUBTLEST]: Colors.gray_40,
    [EIcon.ICON_DISABLED]: Colors.black_a20,
    [EIcon.ICON_INVERSE]: Colors.gray_5,
    [EIcon.ICON_ON_COLOR]: Colors.gray_60,
    [EIcon.ICON_INVERSE_SUBTLE]: Colors.gray_60,
    [EIcon.ICON_INFORMATION]: Colors.blue_50,
    [EIcon.ICON_SUCCESS]: Colors.green_60,
    [EIcon.ICON_ERROR]: Colors.red_50,
    [EIcon.ICON_WARNING]: Colors.orange_50,
    [EIcon.ICON_BRAND]: Colors.yellow_70,
    [EIcon.ICON_INVERSE_CONSTANT]: Colors.gray_100,
  },
};
