import Colors from './colors';

export enum EText {
  'TEXT_PRIMARY' = 'TEXT_PRIMARY',
  'TEXT_SUBTLE' = 'TEXT_SUBTLE',
  'TEXT_SUBTLEST' = 'TEXT_SUBTLEST',
  'TEXT_DISABLED' = 'TEXT_DISABLED',
  'TEXT_ON_INVERSE' = 'TEXT_ON_INVERSE',
  'TEXT_ON_INVERSE_SUBTLE' = 'TEXT_ON_INVERSE_SUBTLE',
  'TEXT_ON_COLOR' = 'TEXT_ON_COLOR',
  'TEXT_ON_COLOR_SUBTLE' = 'TEXT_ON_COLOR_SUBTLE',
  'TEXT_BRAND' = 'TEXT_BRAND',
  'TEXT_INFORMATION' = 'TEXT_INFORMATION',
  'TEXT_SUCCESS' = 'TEXT_SUCCESS',
  'TEXT_ERROR' = 'TEXT_ERROR',
  'TEXT_ON_INVERSE_CONSTANT' = 'TEXT_ON_INVERSE_CONSTANT',
  'TEXT_WARNING' = 'TEXT_WARNING',
  'TEXT_ALPHA' = 'TEXT_ALPHA',
  'TEXT_LABEL_2' = 'TEXT_LABEL_2',
}

export const TEXT_COLOR = {
  dark: {
    [EText.TEXT_PRIMARY]: Colors.gray_1,
    [EText.TEXT_SUBTLE]: Colors.gray_40,
    [EText.TEXT_SUBTLEST]: Colors.gray_60,
    [EText.TEXT_DISABLED]: Colors.white_a25,
    [EText.TEXT_ON_INVERSE]: Colors.gray_100,
    [EText.TEXT_ON_INVERSE_SUBTLE]: Colors.gray_60,
    [EText.TEXT_ON_INVERSE_CONSTANT]: Colors.gray_100,
    [EText.TEXT_ON_COLOR]: Colors.gray_1,
    [EText.TEXT_ON_COLOR_SUBTLE]: Colors.white_a70,
    [EText.TEXT_BRAND]: Colors.yellow_50,
    [EText.TEXT_INFORMATION]: Colors.blue_30,
    [EText.TEXT_SUCCESS]: Colors.green_60,
    [EText.TEXT_ERROR]: Colors.red_50,
    [EText.TEXT_WARNING]: Colors.orange_50,
    [EText.TEXT_ALPHA]: Colors.black_a45,
  },
  light: {
    [EText.TEXT_PRIMARY]: Colors.gray_100,
    [EText.TEXT_SUBTLE]: Colors.gray_60,
    [EText.TEXT_SUBTLEST]: Colors.gray_40,
    [EText.TEXT_DISABLED]: Colors.black_a25,
    [EText.TEXT_ON_INVERSE]: Colors.gray_1,
    [EText.TEXT_ON_INVERSE_SUBTLE]: Colors.gray_40,
    [EText.TEXT_ON_INVERSE_CONSTANT]: Colors.gray_100,
    [EText.TEXT_ON_COLOR]: Colors.gray_1,
    [EText.TEXT_ON_COLOR_SUBTLE]: Colors.white_a70,
    [EText.TEXT_BRAND]: Colors.yellow_70,
    [EText.TEXT_INFORMATION]: Colors.blue_40,
    [EText.TEXT_SUCCESS]: Colors.green_60,
    [EText.TEXT_ERROR]: Colors.red_50,
    [EText.TEXT_WARNING]: Colors.orange_60,
    [EText.TEXT_ALPHA]: Colors.black_a55,
    [EText.TEXT_LABEL_2]: Colors.gray_60,
  },
};
